name: Timestamps
version: '${project.version}'
main: io.github.schmolo.timestamps.Timestamps
api-version: 1.19
load: STARTUP
authors: [ Schmolo, PolyLogic ]
website: schmolo.github.io
commands:
  msg:
    description: Whispers to your given Player.
    usage: /<command> <player> <message>
    aliases: [w, whisper, tell]

  say:
    description: Say something in the Chat.
    usage: /<command> <message>

  ts :
    chatcolor:
      description: Change the Color of you Name
      usage: /<command> chatcolor <[static, gradient, segmented]> <color, starting_color or number_segments> <end_color or color_for_segment> <...>

    prefix:
      description: Add or Change your Prefix
      usage: /<command> prefix <Prefix> <color>